### ISSUE TITLE
No News Articles shown

### ISSUE THREAD

**Issue by rektuk** [purplespider/silverstripe-basic-news#7]
Hello!

I'm struggling right now with the basic-news add on. When I create a new project everything seems to work, I can add new Articles. However, on the webpage there is just a "No News Articles". I also tried dev-master, issue is the same.

I have already used your plugin with ss 3 and there it worked perfectly. When I try to upgrade to ss 5 I had the same issue as described above.

Now, I'm a bit stuck...

I've used the following composer.json

root@test23:/var/www/html# cat composer.json 
{
    "name": "silverstripe/installer",
    "type": "silverstripe-recipe",
    "description": "The SilverStripe Framework Installer",
    "require": {
        "php": "^8.1",
        "silverstripe/recipe-plugin": "~2.0.0@stable",
        "silverstripe/vendor-plugin": "~2.0.1@stable",
        "silverstripe/recipe-cms": "~5.1.0@stable",
        "silverstripe-themes/simple": "~3.3.0@stable",
        "silverstripe/login-forms": "~5.1.0@stable",
        "purplespider/basic-news": "dev-master"
    },
    "require-dev": {
        "phpunit/phpunit": "^9.6"
    },
    "extra": {
        "project-files-installed": [
            ".htaccess",
            "app/.htaccess",
            "app/_config/mimevalidator.yml",
            "app/_config/mysite.yml",
            "app/src/Page.php",
            "app/src/PageController.php"
        ],
        "public-files-installed": [
            ".htaccess",
            "index.php",
            "web.config"
        ]
    },
    "config": {
        "process-timeout": 600,
        "allow-plugins": {
            "composer/installers": true,
            "silverstripe/recipe-plugin": true,
            "silverstripe/vendor-plugin": true
        }
    },
    "prefer-stable": true,
    "minimum-stability": "dev"
}

some additional infos:

root@test23:/var/www/html# php -v
PHP 8.3.3-1+0~20240216.17+debian12~1.gbp87e37b (cli) (built: Feb 16 2024 10:32:28) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.3-1+0~20240216.17+debian12~1.gbp87e37b, Copyright (c), by Zend Technologies
root@test23:/var/www/html# mysql -v
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 121
Server version: 10.11.6-MariaDB-0+deb12u1 Debian 12

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Reading history-file /root/.mysql_history
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> ^DWriting history-file /root/.mysql_history
Bye
root@test23:/var/www/html# uname -a
Linux test23 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux
root@test23:/var/www/html# 

![Screenshot 2024-03-17 at 20 51 24](https://github.com/purplespider/silverstripe-basic-news/assets/163771817/34e67d2d-8811-4b51-b907-d5bf4a95ff0a)

So, hopefully, somebody can point me to the right direction. Thanks!

**Comment by purplespider** [comment]
Looks like the controller name still had an underscore in it (from SS3) and SS5 no longer detects controllers with underscores in the name. I've just fixed this in the latest version, please update to 3.0.2 and try again.

**Comment by rektuk** [comment]
Thank you for the quick fix!
